### ISSUE TITLE
COM port access denied

### ISSUE THREAD

**Issue by bonner72** [tdhoward/COMpipe#11]
First of all thankyou for such a fine free service, everything compiles and runs well. The COMpipe service connects to both the native COM port and the virtual port. My problem is on the virtual machine I get "access to COMport denied" whenever I try to connect something. Is this something you would be able to help with? Thankyou

**Comment by bonner72** [comment]
Okay, my main issue is resolved. Not sure what my problem was, but I'll just attribute it to a late night and a tired brain. What I would like to do is program an Arduino from a Windows XP VM. I can send and receive data from a putty terminal, however I cannot program the arduino. It gives this error: "avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x68". It looks like maybe some timing requirements? At any rate I will keep on working at this issue. If someone with more knowledge than me has any ideas, feel free to share! -Thanks

**Comment by tdhoward** [comment]
Hi @bonner72 , thanks for the nice comments.  I've also done some programming with Arduinos, but never through a VM.  I'm curious if you can program the Arduino from within the host operating system (not on the VM).  If you can, then that may point to an issue in COMpipe transporting the data properly.  Let me know what you find.

**Comment by bonner72** [comment]
Hi, yes I can program the Arduino from the host using the same version of the Arduino IDE as the VM. I did a test with a simple serial echo sketch and anything I type in the serial monitor is returned perfectly. I thought perhaps that the issue with uploading might be linked to the auto reset of the board which the IDE performs just after compiling. However I did also try a manual reset of the board with still no luck. I also tried setting the baud to 115200 which is the speed required by the Arduino bootloader.

Attached is a few pics.
![Port-Capture](https://github.com/tdhoward/COMpipe/assets/99674759/ebcf5656-f73d-4022-af7a-a51bb15b9daf)
![Task-Capture](https://github.com/tdhoward/COMpipe/assets/99674759/d4fc2ea2-b001-4a52-b6ed-e709e16e108e)
![CMD-Capture](https://github.com/tdhoward/COMpipe/assets/99674759/684e1193-e394-40f5-a8d7-c1d1e0b0c7cb)

**Comment by DonWT** [comment]
@bonner72  (Or anybody else?) Did you ever manage to get Arduino development working in a VM?

I have been setting up to do this but have just discovered the issue of accessing the host COM ports from a VM which led me here to COMpipe.

**Comment by bonner72** [comment]
@DonWT , Yes we were able to program and receive data from an Arduino UNO from the VM. However we could not get it to upload with out doing a manual reset of the board. Apparently the USB DTR signal never makes it through.

**Comment by tdhoward** [comment]
@bonner72 That makes sense, since none of the hardware signals (CTS, DTR, etc) are getting transmitted through the named pipe provided by the VM.

**Comment by DonWT** [comment]
I am trying to set up COMpipe to do Arduino development on a Win 11 VM and I cannot figure out how to create the named pipe on the VM.

When I go to settings for the Windows 11 VM in Hyper-V manager then I do not see the COM 1 and COM 2 entries in the hardware section.  I **do** see them in another Windows 10 VM that I have, but nothing in the Win 11 VM.

![image](https://github.com/tdhoward/COMpipe/assets/135274154/d03333f1-2ea8-498b-a6d2-7df6dede617a)


Any ideas on what I am doing wrong or how I can proceed?
