### ISSUE TITLE
Could Not Open Port GLE=2 and ReadFile from pipe failed

### ISSUE THREAD

**Issue by khfiedler57** [tdhoward/COMpipe#14]
Windows 11 Pro

Fehler:

C:\Hyper-V>COMpipe -b 9600 -c COM3 vmcom1 -p pipe vmcom1
Serial port opened successfully.
Exception caught: Could not open pipe. GLE=2
, retrying after 200 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 400 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 800 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 1600 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 3200 milliseconds...
Caught exception after maximum retries: Could not open pipe. GLE=2

Press Q to quit.
ReadFile from pipe failed. GLE=6

**Comment by tdhoward** [comment]
Please review the commandline options, as your command looks to be malformed.
