### ISSUE TITLE
Baud rate is limited to 9600 Baud

### ISSUE THREAD

**Issue by tdhoward** [tdhoward/COMpipe#2]
Ok...further testing revels this is limited to 9600 Baud.  Is there a way to pass a port configuration?  I really need it to go up to 115200, 8, 1, N.

_Originally posted by @sparkyhotm in https://github.com/tdhoward/COMpipe/issues/1#issuecomment-538062850_

**Comment by tdhoward** [comment]
Okay, I believe it should work now. (Commit 46136b7).  Standard port configuration for this utility is 9600, 8, 1, N.  You can now pass the baud rate with the -b option.  My preliminary testing shows it working as expected, but I would appreciate your help testing this, @sparkyhotm.

**Comment by overhome1** [comment]
I have been using your program to pipe a usb com port to a hyper-v Win XP Virtual Machine.  It works great for a terminal program.  However, I run some programs that are sensitive to the flow control (i.e. Xon/Xoff, Hardware, or None).  Normally, these programs operate at 9600-8-N-1 and I don't give flow control much thought except when they (rarely) freeze.  These programs will only work for a few seconds and then freeze using your pipe.  Is there anyway to adjust flow control?  I have tried adjusting the flow control on both the guest and the host machine with a varying amount of success.
Thanks.
