### ISSUE TITLE
Run as a service?

### ISSUE THREAD

**Issue by tdhoward** [tdhoward/COMpipe#3]
Wow - it was a LONG journey to find something free that does this.  Thanks for that.  I just tested on my Hyper-V host 2012 R2 talking to my 2012 R2 Client and it worked fine.  Things I learned: Run as admin.  Don't configure the CLIENT VM COM PORT with a name COMx - COMx is a reserved system device name and makes things not work.  Name your pipe PORTx.  Now, I have to find something that will do this, and run as a service.  Dealing with a serial port in Hyper-V is a PITA.  
Again - Thank you for making this available.

_Originally posted by @sparkyhotm in https://github.com/tdhoward/COMpipe/issues/1#issuecomment-537679058_

**Comment by tdhoward** [comment]
I have a little bit of experience writing Windows services, so I may take a swing at this.  I would really prefer this utility to just come up and run in the background at boot.

**Comment by sparkyhotm** [comment]
Thanks for getting back to me.  I tested a commercially available product  https://freevirtualserialports.com/ and it too would pass keystrokes, but not do a file transfer.  I moved my sending-test host over to my laptop (Prolific USB-to-Serial) and did a hyperterminal transfer just fine, so there's something on the Hyper-V host/Hyper-V Client Pipe that just can't handle the binary data.  Again, my guess is buffers aren't big enough.  Zmodem can send a lot of un-ACK'ed data (wire/port speed) and I'm guessing it's either 1k or 4k blocks.  My Hyper-V host is a healthy HP DL360 Gen 10 - lots of CPU, so I don't think that's an issue.  It's possible the Prolific Drivers are not good, so I'll look into that next.  I'll try a host-to-remote transfer.  If that works, then I'm pressed to believe it's the middle-ware, or Hyper-V Pipe'ing stuff.

On Thu, Oct 3, 2019 at 1:37 PM Tim Howard <notifications@github.com<mailto:notifications@github.com>> wrote:

I have a little bit of experience writing Windows services, so I may take a swing at this. I would really prefer this utility to just come up and run in the background at boot.

**Comment by sparkyhotm** [comment]
and yeah...I could just launch COMpipe as a task manager job, and it should be fine there hidden in the weeds.  Thanks for tweaking for the baud rate.  I didn't notice flow control settings in your app.  XON/XOFF or NONE should be good.  I think HARDWARE might hang things up.

On Thu, Oct 3, 2019 at 1:37 PM Tim Howard <notifications@github.com<mailto:notifications@github.com>> wrote:

I have a little bit of experience writing Windows services, so I may take a swing at this. I would really prefer this utility to just come up and run in the background at boot.

**Comment by alex-calugarescu** [comment]
I used [NSSM](https://nssm.cc/) and it worked really nice on a Hyper V Server.

**Comment by tdhoward** [comment]
> I used [NSSM](https://nssm.cc/) and it worked really nice on a Hyper V Server.

Nice, thanks for the info!  I'll add that to the Readme so other people can run it as a service.
