### ISSUE TITLE
unable start after Windows update KB5011487 

### ISSUE THREAD

**Issue by Rabe04** [tdhoward/COMpipe#5]
After installing Windows update KB5011487 im unable to start compipe.
Windows 10 pro restrictet the start.

**Comment by tdhoward** [comment]
Does it give you an error?

**Comment by Rabe04** [comment]
"This app can’t run on your PC"

in German "diese App kann auf dem pc nicht ausgeführt werden"

On another PC, however, the software runs after the update.
I suspect that this is not a general problem.

**Comment by tdhoward** [comment]
Okay, thanks for the feedback.  I can't duplicate the problem at this time, so if you discover any more details on how to fix this, please post here.  In the meanwhile, you could try the suggestions listed here:
[How to fix this app can't run on your PC](https://helpdeskgeek.com/windows-10/how-to-fix-this-app-cant-run-on-your-pc-in-windows-10/)
