### ISSUE TITLE
How to see pipeline on Linux VM

### ISSUE THREAD

**Issue by giga89** [tdhoward/COMpipe#6]
Ciao @tdhoward .
First of all thanks for your work.
I enabled pipelines and see it on PowerShell (see screenshot below)
![image](https://github.com/tdhoward/COMpipe/assets/1588412/440f8cf9-0635-4610-9025-4462d5a9ad2a)

Turn on compipe on one of pipe
![image](https://github.com/tdhoward/COMpipe/assets/1588412/26109457-970b-47dd-8ac5-1a6182065f74)

So.. How to see it on my linux vm? I am sure that they are "connected" because when I close my VM Compipe close the connection with "Readfile from pipe failed etc etc"

Thanks!

**Comment by tdhoward** [comment]
Hi @giga89 
Are you using Hyper-V for your VM?  I'm assuming you've done the steps to set things up in the VM.

If you have that set up, then I would assume that Linux should be able to use the serial port.  It will likely be something like '/dev/ttys0', not COM1.  But I've never done this with a Linux VM before, so I'm not really sure.
