### ISSUE TITLE
ReadFile from pipe failed. GLE=233

### ISSUE THREAD

**Issue by filamento** [tdhoward/COMpipe#7]
Hi everyone,

I'm trying to redirect a COM port to a Windows Server 2003 virtual machine (running under Hyper-V host), but I get this error every time I restart the virtual machine:

ReadFile from pipe failed. GLE=233

I suspect that Hyper-V destroys the pipe when the VM is shutdown and re-creates it as soon as the virtual machine is restarted.

Is it possible to set a number of retries in COMpipe to allow for VM restarts?

**Comment by tdhoward** [comment]
That is a great idea.  Yes, if Hyper-V restarts the VM, I would assume that it destroys and recreates the pipe.  It would be fairly easy to detect that the pipe went away and try to restart it every 5 seconds, for example.  I'll take a look at that in the next few weeks, unless you want to try taking a swing at it.

**Comment by tdhoward** [comment]
@filamento I believe version 0.2 should take care of your problem. Let me know what you think!

**Comment by filamento** [comment]
Sorry, I've been unable to test until now.

I've been trying this new version, and I've been able to make it work once, but successive attempts always fail. I'm testing on a Server 2019 host (with the Hyper-V role enabled). Maybe that's the problem?

This is the error I'm getting:

COMpipe.exe -c \\.\COM1 -p \\.\pipe\MyPipe
Serial port opened successfully.
Exception caught: Could not open pipe. GLE=2
, retrying after 200 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 400 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 800 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 1600 milliseconds...
Exception caught: Could not open pipe. GLE=2
, retrying after 3200 milliseconds...
Caught exception after maximum retries: Could not open pipe. GLE=2

**Comment by howardtechnical** [comment]
@filamento Could you post the whole text of the command you are using and the messages after it?  I'm wondering if maybe we're just timing out too soon.

**Comment by tdhoward** [comment]
@filamento Could you post the whole text of the command you are using and the messages after it? I'm wondering if maybe we're just timing out too soon.
