### ISSUE TITLE
Windows 11 Pro Problem

### ISSUE THREAD

**Issue by MagentaFocus** [tdhoward/COMpipe#8]
COMpipe looks like its the solution I'm looing for.
However, under Windows 11 23H2 I get

E:\Additions>compipe
This version of E:\Additions\COMpipe.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

I would appreciate if you could take a look. 

Edition	Windows 11 Pro
Version	23H2
Installed on	‎1/‎05/‎2023
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by tdhoward** [comment]
Hmm, that's strange.  I'm running Windows 11 Pro, build 22621 (slightly different), and I'm not seeing the problem.  I'm wondering if it would work for you if you tried compiling it on your machine.  There are no dependencies, so it should be pretty easy to try.  Let me know what you find.

**Comment by MagentaFocus** [comment]
Hello Tim. 
Thanks for the suggestion. 
I'll get a copy of Visual Studio 2022 and give it a try and let you know.

**Comment by MagentaFocus** [comment]
Thanks.
Compiled and started without any issues.
I can't get my (label printer from 1886 with serial interface to works as yet but will give it a go)

**Comment by tdhoward** [comment]
Glad to hear the app started!  Let me know if you run into any other issues with COMpipe.
